### ISSUE TITLE
Add EBNF for BEL v2.0

### ISSUE THREAD

**Issue by cthoyt** [belbio/bel_specifications#1]
Hi @wshayes I found the YAML files, but not the EBNFs. Maybe I'm looking in the wrong place. What do you think?

**Comment by wshayes** [comment]
I added the EBNF files to the github repo. I have other files that I derive from the bel specification files.  Thinking about other ways to host them - leaning towards AWS S3 which can be made publicly readable as an S3 bucket as well as a website.  Github would be the source location for the bel_specification yaml files and the S3 bucket would be the official location for the specification files and any derived files.  If anyone has a better alternative, please let me know.
